// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-tkQCW2MeSL6-LRYIwCWahS3CKAI3Nfg',
    appId: '1:184404646383:web:b74b60303becbfd1077e1a',
    messagingSenderId: '184404646383',
    projectId: 'latihan2-15582',
    authDomain: 'latihan2-15582.firebaseapp.com',
    storageBucket: 'latihan2-15582.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8fWs8HFjv4b39xGJwplF48QreS4ft-oM',
    appId: '1:184404646383:android:68800afacf3b9984077e1a',
    messagingSenderId: '184404646383',
    projectId: 'latihan2-15582',
    storageBucket: 'latihan2-15582.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdvwvAXJk--NMKP8Dg6soleia7IbKkxlg',
    appId: '1:184404646383:ios:b7d1875e4a12414a077e1a',
    messagingSenderId: '184404646383',
    projectId: 'latihan2-15582',
    storageBucket: 'latihan2-15582.appspot.com',
    iosBundleId: 'com.example.latihan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdvwvAXJk--NMKP8Dg6soleia7IbKkxlg',
    appId: '1:184404646383:ios:a4d4a61d981d88e3077e1a',
    messagingSenderId: '184404646383',
    projectId: 'latihan2-15582',
    storageBucket: 'latihan2-15582.appspot.com',
    iosBundleId: 'com.example.latihan.RunnerTests',
  );
}
